name: CASR Runner

on:
  push:

jobs:
  run-casr:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 879fe082dd1f9fe6612f05dba8b8ff4a718040eb
  
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Build project with JDK 17 
      run: ./mvn clean install -DskipTests

    - name: Setup CASR (prerequisites --> macports and cargo)
      run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.7.2.tar.bz2
          tar xf MacPorts-2.7.2.tar.bz2
          cd MacPorts-2.7.2
          ./configure
          make
          sudo make install
          sudo port -v selfupdate
          sudo port install cargo
          cargo install casr

    - name: Run CASR on the .java file(s)
      continue-on-error: true
      run: |      
        set +e
        #!/bin/bash

        directory=$(pwd)
        
        jar_files=$(find "$directory" -type f -name "*.jar")

        for jar_file in $jar_files; 
        do
            command="casr-java --stdout -- java -jar $jar_file"
            $command
        done
